name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build and upload artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: ^7.0.0

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build website
        run: pnpm build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: './build'

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1

